### ISSUE TITLE
Project is misleading

### ISSUE THREAD

**Issue by younisshah** [MAJIDNISAR/TwitterTrends#1]
According to the README, TwitterTrends show
> Based on Geo Location will display twitter trends in that area.

Checking the code in `app.js`, it seems that you are fetching the local weather!

The project is misleading the users!

**Comment by MAJIDNISAR** [comment]
jinab wene chu yi banavnai

**Comment by younisshah** [comment]
Please adhere to GitHub guidelines before creating a repo. I suggest you study this [GitHub Help](https://help.github.com/categories/bootcamp/) guide. Plus, this is not the traditional social commenting system!
